document.writeln("<head>");
document.writeln("<meta http-equiv=\'Content-Type\' content=\'text/html; charset=UTF-8\'>");
document.writeln("<style type=\'text/css\'>");
document.writeln("body{font-size:14px;font-weight:bold;}");
document.writeln("</style>");
document.writeln("</head>");
document.writeln("<body>");
document.writeln("广告：<a id=\'HotNews\' href=\'\' target=\'_blank\'></a>");
document.writeln("<SCRIPT LANGUAGE=\'JavaScript\'>");
document.writeln("<!--");
document.writeln("var NewsTime = 3000;	//每条公告的停留时间");
document.writeln("var TextTime = 100;		//公告标题文字出现等待时间，越小越快");
document.writeln("");
document.writeln("var newsi = 0;");
document.writeln("var txti = 0;");
document.writeln("var txttimer;");
document.writeln("var newstimer;");
document.writeln("");
document.writeln("var newstitle = new Array();	//公告标题");
document.writeln("var newshref = new Array();		//公告链接");
document.writeln("");
document.writeln("newstitle[0] = \'表白网 - 一站式服务\';");
document.writeln("newshref[0] = \'http://www.雅心.我爱你\';");
document.writeln("");
document.writeln("newstitle[1] = \'我爱IT - IT技术分享网\';");
document.writeln("newshref[1] = \'http://www.woai.it\';");
document.writeln("");
document.writeln("newstitle[2] = \'公爵旗舰店 - 雅心官方网店\';");
document.writeln("newshref[2] = \'http://www.晚安.我爱你\';");
document.writeln("");
document.writeln("newstitle[3] = \'领取优惠券 - 低价买买买！\';");
document.writeln("newshref[3] = \'http://www.xiexie.la\';");
document.writeln("");
document.writeln("newstitle[4] = \'站点地图 - 雅心有限公司\';");
document.writeln("newshref[4] = \'http://www.李一洲.中国\';");
document.writeln("");
document.writeln("function shownew()");
document.writeln("{");
document.writeln("	//code by haiwa @2005-10-21 www.51windows.net");
document.writeln("	var endstr = \'_\'");
document.writeln("	hwnewstr = newstitle[newsi];");
document.writeln("	newslink = newshref[newsi];");
document.writeln("	if(txti==(hwnewstr.length-1)){endstr=\'\';}");
document.writeln("	if(txti>=hwnewstr.length){");
document.writeln("		clearInterval(txttimer);");
document.writeln("		clearInterval(newstimer);");
document.writeln("		newsi++;");
document.writeln("		if(newsi>=newstitle.length){");
document.writeln("			newsi = 0");
document.writeln("		}");
document.writeln("		newstimer = setInterval(\'shownew()\',NewsTime);");
document.writeln("		txti = 0;");
document.writeln("		return;");
document.writeln("	}");
document.writeln("	clearInterval(txttimer);");
document.writeln("	document.getElementById(\'HotNews\').href=newslink;");
document.writeln("	document.getElementById(\'HotNews\').innerHTML = hwnewstr.substring(0,txti+1)+endstr;");
document.writeln("	txti++;");
document.writeln("	txttimer = setInterval(\'shownew()\',TextTime);");
document.writeln("}");
document.writeln("shownew();");
document.writeln("//-->");
document.writeln("</SCRIPT>");
document.writeln("</body>");