<?php
$z[0]=Array("global","",254,280);
$z[0][4]=array();
$z[0][4]['name']="cfg_webname";
$z[1]=Array("global","",526,556);
$z[1][4]=array();
$z[1][4]['name']="cfg_description";
$z[2]=Array("global","",596,623);
$z[2][4]=array();
$z[2][4]['name']="cfg_keywords";
$z[3]=Array("global","",640,672);
$z[3][4]=array();
$z[3][4]['name']="cfg_templets_skin";
$z[4]=Array("global","",2186,2218);
$z[4][4]=array();
$z[4][4]['name']="cfg_templets_skin";
$z[5]=Array("global","",2317,2349);
$z[5][4]=array();
$z[5][4]['name']="cfg_templets_skin";
$z[6]=Array("global","",2456,2483);
$z[6][4]=array();
$z[6][4]['name']="cfg_basehost";
$z[7]=Array("channel","\r\n    <li><a href=\"[field:typelink/]\">[field:typename/]</a></li>\r\n    ",2512,2655);
$z[7][4]=array();
$z[7][4]['row']="6";
$z[7][4]['type']="top";

?>